### ISSUE TITLE
Updating to React 0.14

### ISSUE THREAD

**Issue by HelloTiago** [Skyrin/react-starter-kit#1]
First of all, many thanks for such a great React starter kit, I was looking for one that allowed me to get started with per-components-CSS without being too much of a hassle to get started and this is perfect!

So I tried upgrading the packages used here to their latest versions as a few of them are quite a few versions behind and I immediately ran into issues with Babel after that. Since I couldn't fix that, I tried to update just React, however that also lead to a bunch of issues on the browser's console:

<img width="640" alt="screen shot 2015-11-26 at 18 41 23" src="https://cloud.githubusercontent.com/assets/1268955/11429262/6364c2e6-946d-11e5-9a56-d36b291265cc.png">

With that said, do you have any plans to update these packages to their latest (or just newer) versions?
If not, I wouldn't mind giving it another go however I'll definitely need a few pointers.

**Comment by jackmoore** [comment]
Hi Tiago, my apologies for the late reply! This repo is probably not going to be actively maintained, but I did go ahead and update it to use the newer packages. Moving to React 0.14 is no problem, but the React Router api changed a good bit going to 1.0.
